# ===============================================================================
#        _                       _
#   __ _| | __ _ _ __   ___ _ __(_) __ ___  ___   _ ____
#  / _` | |/ _` | '_ \ / __| '__| |/ _` \ \/ / | | |_  /
# | (_| | | (_| | | | | (__| |  | | (_| |>  <| |_| |/ /
#  \__,_|_|\__,_|_| |_|\___|_|  |_|\__,_/_/\_\\__, /___|
#                                             |___/
# ===============================================================================
#
# IMPORTANTE:
#
# Modifique essas configurações APENAS se você tiver certeza do que está fazendo.
#
# ===============================================================================
#
# REQUISITOS NECESSÁRIOS:
#
# É extremamente importante seguir os seguintes passos:
#
# 1. Defina o usuário, senha e nome do banco de dados MongoDB:
#    MONGO_INITDB_ROOT_USERNAME: "your_user"
#    MONGO_INITDB_ROOT_PASSWORD: "your_password"
#    MONGO_INITDB_DATABASE: "neo_database"
#
# Só então execute o comando:
#    $ docker-compose -f mongodb-docker-compose.yml up -d
#
# ===============================================================================

services:
  mongodb:
    image: "mongo:latest"
    container_name: mongodb
    restart: always
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "your_user"
      MONGO_INITDB_ROOT_PASSWORD: "your_password"
      MONGO_INITDB_DATABASE: "your_database_name"

  mongo-express:
    image: "mongo-express:latest"
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      TZ: America/Sao_Paulo
      ME_CONFIG_MONGODB_ADMINUSERNAME: "your_user"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "your_password"
      ME_CONFIG_MONGODB_URL: "mongodb://your_user:your_password@mongodb:27017/your_database_name?authSource=admin"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mongo-express.rule=Host(`mongo.seudominio.com`)"
      - "traefik.http.routers.mongo-express.entrypoints=web,websecure"
      - "traefik.http.routers.mongo-express.tls.certresolver=leresolver"
      - "traefik.http.services.mongo-express.loadbalancer.server.port=8081"      
    depends_on:
      - mongodb

volumes:
  mongodb:

networks:
  default:
    external: true
    name: traefik
