# ===============================================================================
#        _                       _
#   __ _| | __ _ _ __   ___ _ __(_) __ ___  ___   _ ____
#  / _` | |/ _` | '_ \ / __| '__| |/ _` \ \/ / | | |_  /
# | (_| | | (_| | | | | (__| |  | | (_| |>  <| |_| |/ /
#  \__,_|_|\__,_|_| |_|\___|_|  |_|\__,_/_/\_\\__, /___|
#                                             |___/
# ===============================================================================
#
# IMPORTANTE:
#
# Modifique essas configurações APENAS se você tiver certeza do que está fazendo.
#
# ===============================================================================
#
# REQUISITOS NECESSÁRIOS:
#
# É extremamente importante seguir os seguintes passos:
#
# 1. Altere as variáveis relacionadas ao PostgreSQL conforme necessário:
#    DB_POSTGRESDB_HOST: Endereço IP ou nome do host do servidor PostgreSQL
#    DB_POSTGRESDB_DATABASE: Nome do banco de dados PostgreSQL
#    DB_POSTGRESDB_USER: Nome do usuário do PostgreSQL
#    DB_POSTGRESDB_PASSWORD: Senha do usuário do PostgreSQL
#    DB_POSTGRESDB_SCHEMA: Schema do banco de dados PostgreSQL
#
# 2. Altere os campos `n8n.seudominio.com` e `seudominio.com` para os valores 
#    corretos do seu domínio.
#    - "traefik.http.routers.n8n.rule=Host(`n8n.seudominio.com`)"
#
# Só então execute o comando:
#    $ docker-compose -f postgres-docker-compose.yml up -d
#
# ===============================================================================

# Define os serviços que serão executados no Docker
services:

  # Define o serviço do N8N
  n8n:

    # Define a imagem do Docker que será utilizada
    image: n8nio/n8n:1.54.0

    # Nome do container para facilitar identificação
    container_name: n8n  

    # Reinicia automaticamente o container em caso de falha
    restart: always

    # Define as labels para o Traefik
    labels:

      # Habilita o serviço no Traefik
      - traefik.enable=true

      # Define a regra para acessar o N8N
      # Substitua 'n8n.seudominio.com' pelo seu próprio subdomínio
      - "traefik.http.routers.n8n.rule=Host(`n8n.seudominio.com`)"

      # Define o serviço como HTTPS
      - traefik.http.routers.n8n.tls=true

      # Define o certificado SSL para o serviço
      - traefik.http.routers.n8n.entrypoints=web,websecure
      - traefik.http.routers.n8n.tls.certresolver=leresolver
      - traefik.http.routers.n8n.middlewares=n8n@docker

      # Define os middlewares para o serviço
      - traefik.http.middlewares.n8n.headers.SSLRedirect=true
      - traefik.http.middlewares.n8n.headers.STSSeconds=315360000
      - traefik.http.middlewares.n8n.headers.browserXSSFilter=true
      - traefik.http.middlewares.n8n.headers.contentTypeNosniff=true
      - traefik.http.middlewares.n8n.headers.forceSTSHeader=true

      # Define o host para o serviço
      # Substitua 'seudominio.com' pelo seu próprio domínio
      - traefik.http.middlewares.n8n.headers.SSLHost=seudominio.com
      - traefik.http.middlewares.n8n.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.n8n.headers.STSPreload=true

    # Define as variáveis de ambiente
    environment:

      # Define o host
      # Substitua 'n8n.seudominio.com' pelo seu próprio subdomínio
      N8N_HOST: n8n.seudominio.com

      # Define a porta
      N8N_PORT: 5678

      # Define o protocolo
      N8N_PROTOCOL: https

      # Reinstala pacotes automaticamente ao iniciar o N8N
      N8N_REINSTALL_MISSING_PACKAGES: true

      # Define a chave de criptografia
      N8N_ENCRYPTION_KEY: "your_key"

      # Define o ambiente de produção
      NODE_ENV: production

      # Define o webhook
      # Substitua 'n8n.seudominio.com' pelo seu próprio subdomínio
      WEBHOOK_URL: https://n8n.seudominio.com

      # Define o fuso horário do container
      GENERIC_TIMEZONE: America/Sao_Paulo  

      # Define o tipo de banco de dados como PostgreSQL
      DB_TYPE: postgresdb
      
      # Define o endereço IP ou nome do host do servidor PostgreSQL
      DB_POSTGRESDB_HOST: db_ip
      
      # Define o nome do banco de dados PostgreSQL a ser usado
      DB_POSTGRESDB_DATABASE: db_name
      
      # Define o nome do usuário do PostgreSQL
      DB_POSTGRESDB_USER: db_user
      
      # Define a senha do usuário do PostgreSQL
      DB_POSTGRESDB_PASSWORD: db_password
      
      # Define o schema do banco de dados PostgreSQL
      DB_POSTGRESDB_SCHEMA: db_schema

    volumes:
      - ${DATA_FOLDER}/.n8n:/root/.n8n
      - /root/n8n-local-files:/files

networks:
  default:
    name: traefik
    external: true

