# ===============================================================================
#        _                       _
#   __ _| | __ _ _ __   ___ _ __(_) __ ___  ___   _ ____
#  / _` | |/ _` | '_ \ / __| '__| |/ _` \ \/ / | | |_  /
# | (_| | | (_| | | | | (__| |  | | (_| |>  <| |_| |/ /
#  \__,_|_|\__,_|_| |_|\___|_|  |_|\__,_/_/\_\\__, /___|
#                                             |___/
# ===============================================================================
#
# IMPORTANTE:
#
# Modifique essas configurações APENAS se você tiver certeza do que está fazendo.
#
# ===============================================================================
#
# REQUISITOS NECESSÁRIOS:
#
# É extremamente importante seguir os seguintes passos:
#
# 1. Procure a linha abaixo e substitua pelo seu próprio subdomínio:
#    - "traefik.http.routers.portainer.rule=Host(`portainer.seudominio.com`)"
#
# Só então execute o comando:
#    $ docker-compose -f portainer-docker-compose.yml up -d
#
# ===============================================================================

# Define os serviços que serão executados no Docker
services:

  # Serviço Portainer, ferramenta de gerenciamento de containers Docker
  portainer:

    # Define a imagem do Portainer com uma versão específica
    image: portainer/portainer-ce:latest

    # Comandos específicos a serem executados ao iniciar o container
    command: -H unix:///var/run/docker.sock

    # Reinicia automaticamente o container em caso de falha
    restart: always

    # Volumes compartilhados
    volumes:

      # Permite que o Portainer acesse o Docker para gerenciar containers
      - /var/run/docker.sock:/var/run/docker.sock

      # Permite que o Portainer armazene dados persistentes
      - portainer_data:/data

    # Labels para configurar o Traefik
    labels:

      # Habilita o Traefik para gerenciar o Portainer
      - "traefik.enable=true"

      # Define a regra para acessar o Portainer
      # Substitua 'portainer.seudominio.com' pelo seu próprio subdomínio
      - "traefik.http.routers.portainer.rule=Host(`portainer.seudominio.com`)"

      # Acessa o Portainer via HTTPS
      - "traefik.http.routers.portainer.entrypoints=websecure"

      # Define a porta interna do Portainer
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

      # Define o serviço para o Portainer
      - "traefik.http.routers.portainer.service=portainer"

      # Usa o resolver de certificados configurado para HTTPS
      - "traefik.http.routers.portainer.tls.certresolver=leresolver"

# Define os volumes que serão usados pelos serviços
volumes:

  # Volume para armazenar os dados do Portainer
  portainer_data:

# Define a rede externa para o Traefik
networks:
  default:
    external: true
    name: traefik
