# ===============================================================================
#        _                       _
#   __ _| | __ _ _ __   ___ _ __(_) __ ___  ___   _ ____
#  / _` | |/ _` | '_ \ / __| '__| |/ _` \ \/ / | | |_  /
# | (_| | | (_| | | | | (__| |  | | (_| |>  <| |_| |/ /
#  \__,_|_|\__,_|_| |_|\___|_|  |_|\__,_/_/\_\\__, /___|
#                                             |___/
# ===============================================================================
#
# IMPORTANTE:
#
# Modifique essas configurações APENAS se você tiver certeza do que está fazendo.
#
# ===============================================================================
#
# REQUISITOS NECESSÁRIOS:
#
# É extremamente importante seguir os seguintes passos:
#
# 1. Defina o usuário, senha e nome do banco de dados PostgreSQL:
#    POSTGRES_USER: "your_user"
#    POSTGRES_PASSWORD: "your_password"
#    POSTGRES_DB: "your_database_name"
#
# Só então execute o comando:
#    $ docker-compose -f postgres-docker-compose.yml up -d
#
# ===============================================================================

# Define os serviços que serão executados no Docker
services:     

  # Define o serviço do PostgreSQL
  postgres:

    # Define a imagem do PostgreSQL
    image: "postgres:15.8"

    # Nome do container para facilitar identificação
    container_name: postgres  

    # Reinicia automaticamente o container em caso de falha
    restart: always

    # Volumes compartilhados
    volumes:

      # Define o volume para armazenar os dados do PostgreSQL
      - postgres:/var/lib/postgresql/data

    # Mapeamento de portas
    ports:

      # Define a porta do PostgreSQL
      - "5432:5432"

    # Define as variáveis de ambiente
    environment:

      # Define o usuário do PostgreSQL
      POSTGRES_USER: "your_user"

      # Define a senha do PostgreSQL
      POSTGRES_PASSWORD: "your_password"

      # Define o banco de dados do PostgreSQL
      POSTGRES_DB: "your_database_name"

# Define os volumes que serão usados pelos serviços
volumes:

  # Define o volume para armazenar os dados do PostgreSQL
  postgres:

# Define a rede externa para o Traefik
networks:
  default:
    external: true
    name: traefik
