# ===============================================================================
#        _                       _
#   __ _| | __ _ _ __   ___ _ __(_) __ ___  ___   _ ____
#  / _` | |/ _` | '_ \ / __| '__| |/ _` \ \/ / | | |_  /
# | (_| | | (_| | | | | (__| |  | | (_| |>  <| |_| |/ /
#  \__,_|_|\__,_|_| |_|\___|_|  |_|\__,_/_/\_\\__, /___|
#                                             |___/
# ===============================================================================
#
# IMPORTANTE:
#
# Modifique essas configurações APENAS se você tiver certeza do que está fazendo.
#
# ===============================================================================

# Define os serviços que serão executados no Docker
services:

  # Define o serviço
  redis:

    # Define a imagem do Docker que será utilizada
    image: redis:latest

    # Nome do container para facilitar identificação
    container_name: redis
    
    command: >
      redis-server --port 6379 --appendonly yes

    # Define os volumes que serão usados pelos serviços
    volumes:
      - redis-data:/data
      
    ports:
      - 6379:6379
      
# Define os volumes que serão usados pelos serviços
volumes:
  redis-data:
    name: redis-data

networks:
  default:
    name: traefik
    external: true
