# Define os serviços que serão executados no Docker
services:

  # Serviço Portainer, ferramenta de gerenciamento de containers Docker
  portainer:
    # Nome do container para facilitar identificação
    container_name: portainer
    # Define a imagem do Portainer com uma versão específica
    image: portainer/portainer-ce:2.20.1
    # Reinicia automaticamente o container em caso de falha
    restart: always

    # Comandos específicos a serem executados ao iniciar o container
    command:
      # Conecta o Portainer ao Docker através do socket Unix
      - -H unix:///var/run/docker.sock

    # Mapeamento de portas
    ports:
      # Mapeia a porta 9000 do container para a porta 9000 do host (Interface Web)
      - "9000:9000"

    # Volumes compartilhados
    volumes:
      # Permite que o Portainer acesse o Docker diretamente
      - /var/run/docker.sock:/var/run/docker.sock
      # Define onde os dados do Portainer serão armazenados
      - portainer_data:/data

    # Variáveis de ambiente
    environment:
      # Define o fuso horário do container
      - TZ=America/Sao_Paulo

    # Labels para configuração do Traefik
    labels:
      # Habilita o Traefik para gerenciar o Portainer
      - "traefik.enable=true"
      # Define a regra para acessar o Portainer
      # Substitua 'portainer.seudominio.com' pelo seu próprio subdomínio
      - "traefik.http.routers.portainer.rule=Host(`portainer.seudominio.com`)"
      # Acessa o Portainer via HTTPS
      - "traefik.http.routers.portainer.entrypoints=websecure"
      # Define a porta interna do Portainer
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      # Define o serviço para o Portainer
      - "traefik.http.routers.portainer.service=portainer"
      # Usa o resolver de certificados configurado para HTTPS
      - "traefik.http.routers.portainer.tls.certresolver=leresolver"
      # Configura outro host para o Portainer
      # Substitua 'edge.seudominio.com' pelo seu próprio subdomínio
      - "traefik.http.routers.edge.rule=Host(`edge.seudominio.com`)"
      # Acessa o serviço via HTTPS
      - "traefik.http.routers.edge.entrypoints=websecure"
      # Define a porta interna do serviço 'edge'
      - "traefik.http.services.edge.loadbalancer.server.port=8000"
      # Define o serviço 'edge'
      - "traefik.http.routers.edge.service=edge"
      # Usa o resolver de certificados configurado para HTTPS
      - "traefik.http.routers.edge.tls.certresolver=leresolver"

    # Coloca o Portainer na rede pública configurada
    networks:
      - portainer

# Define os volumes que serão utilizados pelos serviços
volumes:
  # Volume para armazenar os dados do Portainer
  portainer_data:

# Define as redes que serão usadas pelos serviços
networks:
  # Usa uma rede Docker já existente chamada 'portainer'
  portainer:
    # O 'external: true' indica que a rede 'portainer' já deve existir previamente.
    # Isso é útil quando você quer que múltiplos serviços compartilhem uma rede
    external: true  
